c07 translation update
IllusionMods/KoikatsuTranslation pull request #150
Opened 2023-09-24 18:46 UTC by ManlyMarco

Thanks to @ScrewThisNoise for providing the translations.

2024-01-05 21:13 UTC, GeBo1 requested changes
Just one to fix

2024-01-05 21:13 UTC, GeBo1 commented on translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/20/202/translation.txt
> +「ん？　『辛すぎてごめんねっ！！　激辛チリソースホットドッグ』だって？」=“Hm? 『Sorry if it's too spicy--!!　Super Spicy Chilly Sauce Hot Dog』”
revert (non-standard whitespace)

2024-01-07 22:28 UTC, ManlyMarco commented on translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/20/202/translation.txt
> +「ん？　『辛すぎてごめんねっ！！　激辛チリソースホットドッグ』だって？」=“Hm? 『Sorry if it's too spicy--!!　Super Spicy Chilly Sauce Hot Dog』”
```suggestion
「ん？　『辛すぎてごめんねっ！！　激辛チリソースホットドッグ』だって？」=“Hm? 『Sorry if it's too spicy--!! Super Spicy Chilly Sauce Hot Dog』”
```

2024-01-08 21:36 UTC, GeBo1 approved these changes

2024-01-08 21:59 UTC, merged